# Site settings
title: Kathy Xu
email: your-email@domain.com
url: https://example.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#505050'
  links: '#2171B3'

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: linkedin
    url: https://www.linkedin.com/in/kathysijingxu
  - title: github
    url: https://github.com/Kat-Attack/Kat-Attack.github.io

# Build settings
markdown: kramdown
permalink: pretty
